# **Einführung in NumPy** **_Introduction to NumPy_**

[NumPy](https://numpy.org/doc/stable/) ist eine grundlegende Python-Bibliothek für numerische Berechnungen. Sie bietet Werkzeuge für die Arbeit mit Arrays, Matrizen und einer Vielzahl von mathematischen Funktionen.

_[NumPy](https://numpy.org/doc/stable/) is a fundamental Python library for numerical computing. It provides tools to work with arrays, matrices, and a host of mathematical functions._

## 1. NumPy Importieren _Import NumPy_

Damit können wir die Funktionen von NumPy verwenden, indem wir ihnen den Präfix `np` voranstellen.

_This allows you to use NumPy’s functions by prefixing them with `np`._

In [5]:
import numpy as np

## 3. Arrays anlegen _Creating Arrays_

In [6]:
# 1D Array (Vector)
arr = np.array([1, 2, 3, 4])
print(arr)

# 2D Array (Matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

# Special Arrays
zeros = np.zeros((2, 3))  # 2x3 array of zeros
ones = np.ones((3, 2))    # 3x2 array of ones
identity = np.eye(3)      # 3x3 identity matrix

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


## 3. Array Operationen _Array Operations_

NumPy ermöglicht elementweise Operationen und unterstützt Matrixoperationen.

_NumPy enables element-wise operations and supports matrix operations._

In [7]:
# Element-wise addition
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
sum_arr = arr_a + arr_b

# Matrix Multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
result = np.dot(matrix_a, matrix_b)

## 4. Indizierung _Indexing_

Der Zugriff auf Elemente funktioniert wie bei normalen Listen in Python.

_Works like normal lists in Python._

In [8]:
# Accessing elements
arr = np.array([10, 20, 30, 40])
print(arr[2])

# Slicing
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[1:4])

# Multidimensional Slicing
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print(arr_2d[1, :])

30
[1 2 3]
[4 5 6]


## 5. Nützliche Funktionenen _Useful Functions_

In [12]:
# Generating Ranges
arr = np.arange(0, 11, 2)  # Array from 0 to 11 (exclusive) with step 2
print(arr)

#Statistical Functions
print(np.mean(arr))  # Mean
print(np.sum(arr))   # Sum
print(np.max(arr))   # Maximum

# Reshaping Arrays
reshaped = arr.reshape((2, 3))  # 2x3 array
print(reshaped)

[ 0  2  4  6  8 10]
5.0
30
10
[[ 0  2  4]
 [ 6  8 10]]


## 6. Erweiterung _Broadcasting_

NumPy expandiert kleinere Arrays automatisch, um sie an die Form größerer Arrays anzupassen.

_NumPy automatically expands smaller arrays to match the shape of larger ones._

In [13]:
arr = np.array([1, 2, 3])
print(arr + 5)

[6 7 8]


## 7. Practical Applications

In [15]:
# Normalizing Data
data = np.array([1, 2, 3, 4])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

# Creating One-Hot Encoded Arrays
categories = 4
indices = np.array([0, 1, 3])
one_hot = np.eye(categories)[indices]
print(one_hot)

[0.         0.33333333 0.66666667 1.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


## 8. Zusammenfassung _Summary_

NumPy ist eine vielseitige Bibliothek für numerische Berechnungen. 
Sie ist die Grundlage für Bibliotheken wie Pandas, Matplotlib und Scikit-learn. 
Die Beherrschung von NumPy ist ein Sprungbrett für fortgeschrittene Data Science und maschinelles Lernen.

>>>
    
_NumPy is a versatile library for numerical computations._
_It is foundational for libraries like Pandas, Matplotlib, and Scikit-learn._
_Mastering NumPy is a stepping stone for advanced data science and machine learning._

[NEXT (Numpy Example)](numpy_sample.ipynb)